### ISSUE TITLE
Headerbar-based vs traditional window decorations don't have the same orientation

### ISSUE THREAD

**Issue by nekohayo** [decathorpe/elementary-stable-rpms#11]
Open, say, gnome-terminal and gnome-tweak-tool (or gnome-calendar and evolution, nautilus and firefox, etc.).

Result: oldschool apps like gnome-terminal, evolution, libreoffice, firefox, have their window decorations reversed from what you would see in GNOME, and thus clash with any application using headerbar (client-side decorations), because the close button is on the left and a maximize button is on the right... instead of harmonizing with headerbar-based apps.

I suspect upstream patched their GTK to hack the headerbar applications instead of the other way around, but we obviously can't do that in Fedora (or any other distro that ships other desktop environments alongside Pantheon).

**Comment by decathorpe** [comment]
I don't think this has something to do with GTK+ patches ... Maybe some settings are out of sync here.

Can you give me the output of the following commands?

```bash
gsettings get org.gnome.desktop.wm.preferences button-layout
gsettings get org.pantheon.desktop.gala.appearance button-layout
gsettings get org.gnome.settings-daemon.plugins.xsettings overrides
```

**Comment by nekohayo** [comment]
```
$ gsettings get org.gnome.desktop.wm.preferences button-layout
'appmenu:close'

$ gsettings get org.pantheon.desktop.gala.appearance button-layout
'close:maximize'

$ gsettings get org.gnome.settings-daemon.plugins.xsettings overrides
@a{sv} {}
```

**Comment by decathorpe** [comment]
Well, this confirms my suspicions then.

I really don't want to make a decision here (because no matter what I do, someone will be angry ...), but I really *don't* like the 'close:maximize' button layout that elementary defaults to. So, I am inclined to set the gala default setting to 'appmenu:close' (like the GNOME default) with a downstream patch or override ...

What do you think?

**Comment by ziflex** [comment]
I switched to Panthon's original position (left side) using dconf editor.

**Comment by juanfgs** [comment]
little late to the party, in my configuration no matter what the appmenu is always displayed on the right. If I put it like "appmenu:close" I get the close button on the right side, and the appmenu next to it. For now I've settled to leave it like "close:appmenu" since it's the least odd-looking setup.

**Comment by decathorpe** [comment]
elementary's applications don't make use of the "configurable" GNOME appmenu, but have hard-coded a menu on the right side of the header bar. GNOME applications should respect the "appmenu:close" setting, but elementary applications won't.

And since I didn't get any objections to my proposal above, I'll go ahead and patch the gala default to be "appmenu:close".

**Comment by decathorpe** [comment]
Ok, so, starting with the following builds / updates of gala, the default window buttons match the fedora GNOME default settings:

- `gala-0.3.0+git171217.173134.439fdf6e-3` in the elementary-nightly COPR repo ([build](https://copr.fedorainfracloud.org/coprs/decathorpe/elementary-nightly/build/692735/))
- `gala-0.3.0-0.git139.439f.2.fc28` on rawhide ([build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1012811))
- `gala-0.3.0-0.git139.439f.2.fc28` on fedora 27 ([update](https://bodhi.fedoraproject.org/updates/FEDORA-2018-2af03493b7))
- `gala-0.3.0-0.git139.439f.2.fc26` on fedora 26 ([update](https://bodhi.fedoraproject.org/updates/FEDORA-2018-3ab33d0e25))
